Switch to dor-services-client for initial_workflow.
sul-dlss/item-release pull request #127
Opened 2019-03-14 12:56 UTC by justinlittman

closes #126

2019-03-14 13:25 UTC, jcoyne commented
We need to add this to https://github.com/sul-dlss/common-accessioning/pull/157

2019-03-14 13:27 UTC, jcoyne requested changes

2019-03-14 13:27 UTC, jcoyne commented on spec/lib/dor/item_spec.rb
> +    # allow(Dor::WorkflowObject).to receive(:initial_workflow).with(Dor::Config.release.workflow_name).and_return(true)
Cruft?

2019-04-10 21:36 UTC, aaron-collier commented
@justinlittman can this be closed now in favor of: https://github.com/sul-dlss/common-accessioning/pull/202

2019-04-11 12:06 UTC, closed without merging